version: "3.8"
services:
  spring-starter:
    build: .
    # We need to either restart or timout since "No connections until MySQL init completes"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      MYSQL_HOST: database

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: enabled
      MYSQL_DATABASE: exman
      MYSQL_USER: exman
      # This CLEARLY is insecure and should read from the native ENV variable or a secret store
      MYSQL_PASSWORD: c73cb3o9c37cb3uc397c

  adminer:
    image: adminer
    depends_on:
      - database
    restart: always
    ports:
      - "8081:8080"

  unleash:
    image: unleashorg/unleash-server
    # username: admin
    # password: unleash4all
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: "postgres://postgres:unleash@db/postgres"
      DATABASE_SSL: "false"
      DATABASE_PORT: "5433"
    depends_on:
      - db
    command: npm run start
    healthcheck:
      test: ["CMD", "nc",  "-z", "db", "5433"]
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s
  db:
    expose:
      - "5433"
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres", "--host=127.0.0.1", "--port=5432"]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s

