# Basic dXNlcjpwYXNzd29yZA== is the result of base64 encoding the phrase "user:password"
# https://www.base64encode.org/
GET /employees/ HTTP/1.1
Host: localhost:8080

###

GET /secure-employees/ HTTP/1.1
Host: localhost:8080
Authorization: Basic dXNlcjpwYXNzd29yZA==
