name: Container Scan
on:
  schedule:
    - cron: '0 2 * * 0'
  pull_request:
    branches:
      - main
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build
        name: Build application
      - run: docker build . -t ndshfswe.azurecr.io/spring-starter:${{ github.sha }}
        name: Build docker image
      - uses: Azure/container-scan@v0
        name: Scan docker image
        with:
          severity-threshold: MEDIUM
          image-name: ndshfswe.azurecr.io/spring-starter:${{ github.sha }}
